### ISSUE TITLE
Cannot read from register in insert mode with macro

### ISSUE THREAD

**Issue by nicolaiskogheim** [junegunn/vim-peekaboo#11]
### What
Running a macro that does \<C-R> in insert mode to read from register does not work, and returns empty string - not contents of register.
Bug is only visible when running macro, not when recording it.

### My setup
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov  9 2014 22:01:23)
MacOS X (unix) version
Included patches: 1-488
Compiled by Homebrew
[The settings in my vimrc (mappings and functions removed)](https://gist.github.com/nicolaiskogheim/af2c2136e485c10b2bd0)
Tested without other plugins.
Cannot reproduce with peekaboo plugin disabled.

### How to reproduce
Record a macro that reads from a register in **insert mode** like this:
`<C-R><register>`

So, with 'hello' in the " register, this command `qqi<C-R>"<ESC>q`, writes 'hello', and is working as expected.

The issue emerges when running the macro with `@q`.

**Expected**: `hello` is printed
**Actual**: nothing is printed, and the bell rings (visuall and sound bell from terminal)

Possibly related:
If you do exactly the same as above, but add \<C-P> after \<C-R> and before ", then the `"` will be written out instead of nothing.

Off topic trivia:
When using `<C-R><register>` in a macro, you will paste whatever was in the register at the time of recording.
When you use `<C-R><C-P><register>`, you will paste whatever is in the register when you run the macro.

**Comment by junegunn** [comment]
One thing I know from experience is that `feedkeys()` does not work well with macros.
I pushed a commit to [fix-11](https://github.com/junegunn/vim-peekaboo/tree/fix-11) branch that temporarily disables mappings when replaying a macro. Could you try it and see if it solves your problem? Also let me know if you see any other side-effect of the change.

**Comment by junegunn** [comment]
Merged the branch to master.
