### ISSUE TITLE
Strange behaviour with register in macro, normal mode

### ISSUE THREAD

**Issue by nicolaiskogheim** [junegunn/vim-peekaboo#12]
This is a nasty one. And I'm not even sure of what is going on.

### What
Special sequence of commands, involving moving a line up/down, pasting from a specified register, and moving back, produces strange output.

### My setup
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov  9 2014 22:01:23)
MacOS X (unix) version
Included patches: 1-488
Compiled by Homebrew
[The settings in my vimrc (mappings and functions removed)](https://gist.github.com/nicolaiskogheim/af2c2136e485c10b2bd0)
Tested without other plugins.
Cannot reproduce with peekaboo plugin disabled.

### Macros that trigger the bug
These produce the exact same output when peekaboo is enabled.
*Should paste a word under the cursor*
- `o^[""pk`
- `$a^M^[""pk`
- `j""pk`
*Should paste a word over the cursor*
- `k""pj`

### How to reproduce
1. Fill the " register with the word `YES`
2. Record this macro `o^[""pk`, or one from the list above (or just yank it into the q register)
3. Go to the start of a line with text on (text makes it easier to see, but is not required)
4. Run the macro

**Expected**:
```
some text that was here before
YES
```

**Actual**:
```
sYESome text that was here before
(empty line inserted from the  o-command, if you used the macro with an o-command)
```

*Notes*:
The bug **does** occur for other registers than the one used in the example.
The bug **does not** occur if you paste without specifying register with "<reg>.
The bug **does not** occur if you don't move back to the starting line. So this macro does not trigger it: `k""p` (the same as the last macro in the list of macros, but without the `j` for returning to the line).

**Comment by junegunn** [comment]
Thanks for the details report! #13 seems to fix this as well. Let me know if you still see the problem after the update.
