### ISSUE TITLE
Release 0.1?

### ISSUE THREAD

**Issue by lkraav** [junegunn/vim-peekaboo#14]
Hi. Peekaboo looks fascinating. Can I get a git tag so I can send my package managers to pull the plugin with a version number? Tyvm sir

**Comment by junegunn** [comment]
I usually don't tag my plugins these days, as most Vim users just prefer to update to the latest version, but yeah, why not.

**Comment by junegunn** [comment]
0.1.0 is up!

**Comment by lkraav** [comment]
Thanks. Package management is still a rather optimal way to multiply a single configuration across machines without bolting on an external update strategy. I'd definitely appreciate it if every once in a while a tag would be pushed, no matter how random from a QA perspective.

**Comment by junegunn** [comment]
I'm not completely sure what you mean by "Package management", it's a rather broad term. But judging from your comment, it looks like you can just use commit hashes instead of tags for that purpose, though I don't object tagging.

**Comment by junegunn** [comment]
In case you didn't know, GitHub allows you to download archive at any point:

https://github.com/junegunn/vim-peekaboo/archive/0.1.0.tar.gz
https://github.com/junegunn/vim-peekaboo/archive/master.tar.gz
https://github.com/junegunn/vim-peekaboo/archive/3517518.tar.gz
https://github.com/junegunn/vim-peekaboo/archive/c21c5b1.tar.gz
...

**Comment by lkraav** [comment]
By package mgmt I mean distibution package mgmt: apt, portage, yum etc etc. Not pulling directly from the source repo.

Yep, and those archive URLs are exactly what I needed to get with the tag.

**Comment by lkraav** [comment]
Everything above still applies, would be useful if some kind of tags could be produced. PS to lower the burdain of managing semantic versions etc crap, you could just use date-based stamps a la `20160820` for whatever state you think is stable enough. This will work fine for all distribution package managers.
