### ISSUE TITLE
Register 0 is shown wrong

### ISSUE THREAD

**Issue by gelguy** [junegunn/vim-peekaboo#17]
Register 0 is shown wrong in the peekaboo window.

https://github.com/junegunn/vim-peekaboo/blob/master/autoload/peekaboo.vim#L32

This is caused by Vim's string equality, `0 == '%'` is true. So for register 0, register '%' is printed instead. This can be fixed by checking that the register is a Number or using a regex.

**Comment by junegunn** [comment]
Whoa, it was a nasty bug. Thanks for tthe report!
