### ISSUE TITLE
Cmap for <Plug>(pkbcr)

### ISSUE THREAD

**Issue by gelguy** [junegunn/vim-peekaboo#18]
Peekaboo is able to integrate with [Cmd2.vim](https://github.com/gelguy/Cmd2.vim) to allow Peekaboo to be called in command mode.

The only missing thing is that `<Plug>(pkbcr)` is not `cnoremap`-ped. Is it possible to put this as a default mapping to allow for a seamless integration?

**Comment by junegunn** [comment]
Could you send me a PR? If the required change is trivial and it doesn't affect the users who don't use the plugin, I'll merge it.

**Comment by gelguy** [comment]
Fixed by #19.

Since peekaboo does not work in command mode normally, the `cmap` should not affect existing functions.

**Comment by junegunn** [comment]
Merged. Could you show how one can enable peekaboo on command line using cmd2.vim?

**Comment by gelguy** [comment]
Thanks!
