### ISSUE TITLE
Looking for a suggestion when running a macro on a bunch of lines

### ISSUE THREAD

**Issue by shmup** [junegunn/vim-peekaboo#24]
I love using this plug-in, but sometimes I might be doing a thing like:

`:'<,'>normal @q`

And so as this runs on every line I have to see the peekaboo panel toggle open and closed every time it executes the @q.

Do you have any suggestions for how you might handle a thing like this? I'm thinking maybe I should just have a function that I can call to toggle peekaboo on/off.

Not sure, though.

**Comment by junegunn** [comment]
Does `normal! @q` (normal with exclamation mark) help?

**Comment by shmup** [comment]
Ha! Yes that is perfect and I forgot about that.

Thanks. :}

**Comment by junegunn** [comment]
:)

Also, setting `g:peekaboo_delay` might help in some cases.
