### ISSUE TITLE
@ only works for the first time

### ISSUE THREAD

**Issue by lazywei** [junegunn/vim-peekaboo#26]
If I press `@ap`, the peekaboo window will show. However, after that, the `"` and `@` will fail to work. No window will show.

**Comment by junegunn** [comment]
Since peekaboo temporarily disables itself during `@`-replay, it is possible that it fails to reenable itself depending on the content of the register. What was in `@a`?

**Comment by junegunn** [comment]
I changed how peekaboo disables itself during `@`. Please update and let me know if it helps.

**Comment by lazywei** [comment]
Sorry for the late reply. `@` did display the menu. However, it seems it use `*` register only. That is `@ap`, @3p` will always paste the content in `*`. I'm not sure if this is relevant to this plugin though.

Thanks

**Comment by junegunn** [comment]
Why do you use `@` for that? You should be doing `"3p` or `"ap`.

`@3p` is recognized as `@3` (replay the macro in register 3) and `p` (paste the content in the default register)

**Comment by lazywei** [comment]
Oh... you're right. I totally misunderstand it. I thought peekaboo
rewrite `@`'s behavior. I think this issue can be closed then.
Close #26.
Thanks :-)
-- Chih-Wei (Bert)


2015-05-07 10:59 GMT+08:00 Junegunn Choi <notifications@github.com>:
