### ISSUE TITLE
Peekaboo breaks commandline window

### ISSUE THREAD

**Issue by rafaeln** [junegunn/vim-peekaboo#27]
If you enter the commandline window (with q: or :<C-F>) and then try to paste something there, you get this series of errors:

![image](https://cloud.githubusercontent.com/assets/2940362/7398461/8adfe1ae-ee85-11e4-895b-93d7c4a7d32d.png)

For the time being I am fixing this by setting a delay for peekaboo, but I thought you could implement in the commandline window the same behavior it has on the commandline, namely, be inactive.

Thanks for the great plugin!

**Comment by junegunn** [comment]
Thanks for the report. Fixed it so that the mappings are not defined on command-line window. Let me know if you see any other issue.

**Comment by rafaeln** [comment]
This fixed this issue. Thanks!
