### ISSUE TITLE
pasting in the expression register `"=`

### ISSUE THREAD

**Issue by rafaeln** [junegunn/vim-peekaboo#28]
If I enter in the expression register `"=`, either by doing `<C-R>=` in insert mode or `"=` in normal mode, and then try to paste something, as soon as I press `"`, the text `Peekaboo` is written on the commandline, and I can't paste anything unless I do the workaround of entering the commandline window with `<C-F>`.

**Comment by junegunn** [comment]
Hmm, I can't seem to reproduce. Are you running the latest version?

**Comment by rafaeln** [comment]
I was mistaken. This is not `vim-peekaboo`'s fault. It's actually `Cmd2.vim`'s fault. I would suggest, though, adding a note to `vim-peekaboo`'s FAQ saying that if you use decide to use `Cmd2.vim` to implemente `vim-peekaboo` in commandline mode, you'll have issues pasting at all in the `expression register commandline`.
