### ISSUE TITLE
gvim window shrinking

### ISSUE THREAD

**Issue by buchmoyerm** [junegunn/vim-peekaboo#31]
As my peekaboo window opens and closes my gvim window slowly get more and more narrow. There a resize happening that is causing my window to shrink

**Comment by junegunn** [comment]
Thanks for the heads up. I don't use gvim so I wasn't aware of the issue. I'll take a look when I get a chance.

**Comment by buchmoyerm** [comment]
Just saw gvim shrinking without peekaboo installed. Seems to be fixed by hiding the gui vertical scroll bar. (I've stopped using the gvim gui completely as well so I haven't tested to confirm if removing the scroll bar fixes this issue, but I'm going to close under the assumption that it does).
