### ISSUE TITLE
Also for marks?

### ISSUE THREAD

**Issue by michamos** [junegunn/vim-peekaboo#32]
Hi,

Peekaboo is very convenient since it removes the need to remember what is stored in which register.
I think it would be very useful to have a similar mechanism for marks. Indeed marks are conceptually quite similar to registers, in the sense that there is a whole list of automatic and manual marks at different positions and it is often difficult to remember where every mark is located.
Do you think it would be possible to extend peekaboo (or create another plugin along the same concept), but with marks instead of registers?

**Comment by junegunn** [comment]
Yes, it should be possible, but please be warned; I have learned from my experience that overriding the default behavior of Vim leads to many subtle issues that are very difficult or even impossible to fix (see the open issues of peekaboo), and you end up with a bunch of crazy hacks. So, having said that, I'm not currently interested in extending peekaboo anymore, but feel free to fork it if you want. And I'm pretty sure there are other plugins for marks though I don't use one.

**Comment by jdhao** [comment]
@michamos , there is a plugin called [vim-markbar](https://github.com/Yilin-Yang/vim-markbar) which does what you want.
