### ISSUE TITLE
Open peekaboo in current window

### ISSUE THREAD

**Issue by rohanorton** [junegunn/vim-peekaboo#33]
Hi,

Firstly, just want to say that I really love this plugin, it's a great idea and seems to be very well implemented. Thank you!

The issue that I'm having is that I'd like to open the peekaboo window in the current buffer window instead of in a separate split. I've attempted to use the `g:peekaboo_window` variable, but couldn't figure out how to do anything with it other than split windows.

Is it possible to achieve this with the plugin as it exists?

If not, it's a feature that I'd really like, as opening a split if often not desirable on wide monitors. I understand you might not have the time / desire to do this, in which case I'd be happy to fork it and attempt to implement it myself.

Thanks

**Comment by junegunn** [comment]
Hi, I've just pushed a fix that fixes several issues with non-default `g:peekaboo_window` values. With the fix, you can now use `let g:peekaboo_window = 'enew'`. Let me know if it doesn't work as expected.

**Comment by rohanorton** [comment]
Perfect. Thanks so much :)
