### ISSUE TITLE
Using expression register in an abbreviation fails

### ISSUE THREAD

**Issue by TheLocehiliosan** [junegunn/vim-peekaboo#34]
The following abbreviation is broken when using `vim-peekabo`.

```
iabbr tdate <c-r>=strftime("%Y-%m-%d")<cr>
```

When `vim-peekaboo` is installed, the text inserted is literally `strftime("%Y-%m-%d")`.

**Comment by junegunn** [comment]
Have you tried `inoreabbrev`?
https://github.com/junegunn/vim-peekaboo#peekaboo-conflicts-with-my-maps-and-abbrevs

**Comment by TheLocehiliosan** [comment]
Thanks. Yes, the no remapping version works properly. My bad. Thanks for the plugin. :)
