### ISSUE TITLE
Temporarily disabling peekaboo when dealing with extremely large registers

### ISSUE THREAD

**Issue by pj** [junegunn/vim-peekaboo#35]
Hi, while using peekaboo I've hit problems when one of the registers contains a lot of data, is there a way to temporarily disable peekaboo?

**Comment by junegunn** [comment]
Interesting problem.
There's no automatic way to do that, but if it's sufficient to do it manually, you can call `peekaboo#on()` or `peekaboo#off()` functions which maps/unmaps bindings.

See https://github.com/junegunn/vim-peekaboo/blob/master/plugin/peekaboo.vim
