### ISSUE TITLE
":'<'>normal q@" hangs

### ISSUE THREAD

**Issue by jiyyt** [junegunn/vim-peekaboo#36]
1. Record a simple macro: qq0fe~q
2. Visually select a few lines: Vjjj
3. Play back the macro on the selected lines: :'<,'>normal @q

Vim version 7.4.692 hangs.

**Comment by junegunn** [comment]
Hmm, thanks for the report. Not sure why this happens. In this particular case using `normal!` instead of `normal` fixes the problem, but it's just a workaround and I'll see if there's a better way to handle this.

**Comment by markwu** [comment]
I have the same issue, but using `normal!` fix this problem. Thanks for the tip.

**Comment by kyounger** [comment]
I can confirm this bug and the `normal!` fixes it.

**Comment by NightVigil** [comment]
Same, but `normal!` is a workaround, not a fix. I notice that it doesn't just hang, but uses 100% CPU.
