### ISSUE TITLE
neovim: i_CTRL-r at end of line broken

### ISSUE THREAD

**Issue by blueyed** [junegunn/vim-peekaboo#37]
I've noticed that with Neovim, <C-r> (e.g. `<c-r>*`) in insert mode at the end of line will insert the register not at the end, but one character before it.

```
foo_
=> fobar_o
```

Can you confirm this?

**Comment by junegunn** [comment]
Hmm, yeah, I can see that happens, but strangely, not always. On some lines it just works fine. Not sure what makes the difference.

**Comment by vbauerster** [comment]
Could this help?
CTRL-\ CTRL-O	like CTRL-O but don't move the cursor	     *i_CTRL-\_CTRL-O*

**Comment by blueyed** [comment]
Sounds good.
Reminded me of https://github.com/neovim/neovim/issues/5805, also unrelated probably.

**Comment by blueyed** [comment]
As for me, I am not using peekaboo currently anymore, so feel free to close it.

**Comment by junegunn** [comment]
@vbauerster Thanks for the nice suggestion. Fixed it.
