### ISSUE TITLE
highlight default link peekabooSelected Todo a poor choice for many colorschemes

### ISSUE THREAD

**Issue by mtglsk** [junegunn/vim-peekaboo#38]
`hi peekabooSelected cterm=reverse` Would work with most colorschemes (but not look as good probably, but i am running into cases when the selected register renders black on black with many themes. Maybe drop the highlight group completely?

**Comment by junegunn** [comment]
Todo looks good to me with the color schemes that I use, but YMMV. But you can customize it, right?
You can try this:

```vim
hi peekabooSelected cterm=NONE
```

**Comment by mtglsk** [comment]
Closing it.
