### ISSUE TITLE
Option to zoom window

### ISSUE THREAD

**Issue by jeetsukumaran** [junegunn/vim-peekaboo#4]
Is there a way to temporarily maximize the view, perhaps by pressing a key that would never be used following `"` or `@` (maybe `<SPACE>`)?

**Comment by junegunn** [comment]
Thanks, I like the idea, I'll look into it later in the day.

**Comment by junegunn** [comment]
Now spacebar will toggle fullscreen mode as you requested. Let me know if you see any issues. Thanks!

**Comment by jeetsukumaran** [comment]
Thanks. Appreciate it!
