### ISSUE TITLE
Vim register is full of '../' I think it is netrw but could it be peekaboo?

### ISSUE THREAD

**Issue by CrashyBang** [junegunn/vim-peekaboo#40]
Sorry I swear I am going to stop logging issues on all of your awesome plugins after this one.

Basically when I show the `peekaboo` register it is full of `../` and `../../` it gets worst after using `netrw`

Any ideas, could be related to this: https://github.com/kien/ctrlp.vim/issues/648

I have disabled any lines related to my clipboard.

Cheers.
Otis.

**Comment by CrashyBang** [comment]
Hey @junegunn,

Figured it out was to do with tpope/vim-vinegar and `set hidden`

Cheers,
Otis.

**Comment by junegunn** [comment]
That's strange. Good to know anyway. Thanks.
