### ISSUE TITLE
vsplit same buffer: unpredictable paste in insert mode

### ISSUE THREAD

**Issue by vbauerster** [junegunn/vim-peekaboo#43]
I often edit the same buffer in vertical split. When I try to paste in insert mode <kbd>CTRL</kbd>+<kbd>R</kbd>, while in the right pane, the cursor jumps to left pane, and pasted word appears in random area.

Here I try to delete word del to paste()
![step 1](https://s25.postimg.org/mi6jybvm7/Screen_Shot_2016_08_04_at_19_27_27.png)
Here my cursor in between parens: paste(|), while in insert mode I press <kbd>CTRL</kbd>+<kbd>R</kbd>+<kbd>-</kbd>
![step 2](https://s25.postimg.org/l4ex30wcv/Screen_Shot_2016_08_04_at_19_27_57.png)
The result:
![step 3](https://s25.postimg.org/wqz145jnz/Screen_Shot_2016_08_04_at_19_26_39.png)

**Comment by junegunn** [comment]
Thanks for the report. I'll see what I can do.

**Comment by junegunn** [comment]
Pushed the fix. Please update and see if it helps. Thanks.

**Comment by vbauerster** [comment]
Indeed fixed! Thank you for your invaluable work!
