### ISSUE TITLE
Question: format for g:peekaboo_window

### ISSUE THREAD

**Issue by al3xandru** [junegunn/vim-peekaboo#45]
My apologies for asking this question here, but I couldn't find how to configure the position of the peekaboo window. I noticed the setting `g:peekaboo_window` but it's not clear to me what format I should use for that.

I wanted to make the peekaboo_window show up at the top in a horizontal split, so my failed attempt was:

```
let g:peekaboo_window='split topleft'
```

thanks

**Comment by junegunn** [comment]
You can use `topleft new`. See `:help topleft` and `:help new` for the details.

**Comment by al3xandru** [comment]
Thank you. I did check the help following the lead from `botright` but I missed the `new` part.
