### ISSUE TITLE
Vim / Neovim install error / solution

### ISSUE THREAD

**Issue by victoriastuart** [junegunn/vim-peekaboo#57]
**Issue:** Failed to install in Vim (Neovim) using the approach listed.

Aside:

```
## Symlinks (to use Vim settings with Neovim):
ln -s ~/.vim ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim
```

**Solution:** I manually recreated the `autoload | plugin | syntax` directory structure shown at https://github.com/junegunn/vim-peekaboo in /home/victoria/.vim/ (copied raw files/code to those locations).

In my case, I needed to create the /home/victoria/.vim/plugin/ and /home/victoria/.vim/syntax directories.

```
[victoria@victoria .vim]$ tree -L 2 -F ~/.vim -I 'bundle*|init*|readme*|spell*|swap|undo|view|vim*'
/home/victoria/.vim
├── autoload/
│   ├── pathogen.vim
│   └── peekaboo.vim
├── plugin/
│   └── peekaboo.vim
└── syntax/
    └── peekaboo.vim
```

**Comment by junegunn** [comment]
This is a general Vim plugin question rather than an issue specific to vim-peekaboo. And since you're not following the instruction on the README page (using vim-plug), I suggest that you ask this on https://vi.stackexchange.com/ instead.
