### ISSUE TITLE
when this plugin be loaded lazy will occur some problem

### ISSUE THREAD

**Issue by Freed-Wu** [junegunn/vim-peekaboo#65]
```
	call dein#add('junegunn/vim-peekaboo', {
				\ 'on_map': ['"', '@'],
				\ })
```

when type '@' or '"', nothing will occur. utill user `:edit` to refresh, the plugin will work.

Thank you!

**Comment by junegunn** [comment]
You should report this to the issue tracker of your plugin manager.
