### ISSUE TITLE
change location of sidebar?

### ISSUE THREAD

**Issue by gilbh** [junegunn/vim-peekaboo#85]
Hi,

Is it possible to open the sidebar on the left side of the screen and not on the right?

Thanks!

**Comment by Gee19** [comment]
You can achieve this by modifying [this command](https://github.com/junegunn/vim-peekaboo/blob/master/autoload/peekaboo.vim#L28) from `botright` to `topleft`

**Comment by gilbh** [comment]
That's great, thanks!!
