### ISSUE TITLE
Error when loclist is open

### ISSUE THREAD

**Issue by tthbellcom** [junegunn/vim-peekaboo#9]
Hi!

I get the following error when using peekaboo with an open loclist (opened by syntastic). 

![peekaboo_loclist_error](https://cloud.githubusercontent.com/assets/1716867/6184069/84cafbfe-b35d-11e4-9138-51c59c2fd5ba.png)

The peekaboo scratch buffer opens as expected, when pressing ", put as soon as i select a register, the cursor jumps to the loclist and i get the error in the screenshot.

**Comment by tthbellcom** [comment]
Quick followup. As i see it, it happens when peekaboo tries to highligt the selected register.

**Comment by junegunn** [comment]
Hi, I can't seem to reproduce the error. Could you try it again with a minimal vimrc without any other plugins or settings except syntastic and peekaboo? Something like this:
```vim
vim -Nu <(cat << EOF
set rtp+=~/.vim/plugged/vim-peekaboo
set rtp+=~/.vim/plugged/syntastic
EOF
)
```

**Comment by tthbellcom** [comment]
Narrowed it down to syntastics auto loclist feature causing the error. 
```vim
let g:syntastic_auto_loc_list=1
```

I'm not sure if this is an issue for peekaboo or syntastic?

**Comment by junegunn** [comment]
Thanks for narrowing down the problem. It was not peekaboo's fault, but I told peekaboo to be forgiving to its inconsiderate neighbors. It won't happen again.

**Comment by tthbellcom** [comment]
Epic comment :laughing: Thanks for the quick response! `:PlugUpdate`
